In [1]:
import pandas as pd

### Crear datafame

In [2]:
# pd.DataFrame({'columna_1':[1,2,3,4], 'columna_2':['a','b','c']}) # ERROR tienen que ser del mismo tamano
#
pd.DataFrame({'columna_1':[1,2,3], 'columna_2':['a','b','c']}) # index desde cero por default

   columna_1 columna_2
0          1         a
1          2         b
2          3         c

In [3]:
pd.DataFrame(
    {'columna_1':[1,2,3], 'columna_2':['a','b','c']},
    # index=range(3,6)
    index=['a1','a2','a3']
    )

    columna_1 columna_2
a1          1         a
a2          2         b
a3          3         c

### Series

In [4]:
pd.Series([1,2,3,4,5,6,7,8,9,10])

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [5]:
pd.Series(range(4))

0    0
1    1
2    2
3    3
dtype: int64

In [6]:
pd.Series(range(1,4), index=['primero', 'segundo', 'tercero'])

primero    1
segundo    2
tercero    3
dtype: int64

In [7]:
pd.Series(range(1,4),
          index=['primero', 'segundo', 'tercero'],
          name='lista')

primero    1
segundo    2
tercero    3
Name: lista, dtype: int64

### Leer Archivos

In [8]:
#  el archivo mas comun es el de csv
df = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [9]:
# tamano del dataframe
df.shape

(3000, 9)

In [10]:
# las primeras 5 filas
df.head()

# las ultimas 5 filas
df.tail()

# una fila random
df.sample(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
1338,-122.70,39.14,13.0,532.0,111.0,214.0,62.0,3.3929,108300.0
950,-121.88,37.32,38.0,1787.0,508.0,2113.0,530.0,2.6386,177600.0
2637,-122.27,37.84,52.0,1688.0,337.0,853.0,325.0,2.1806,99700.0
2188,-118.47,34.00,38.0,1235.0,390.0,891.0,376.0,2.7143,287500.0
1124,-117.19,32.77,30.0,2747.0,640.0,3185.0,657.0,3.7650,238000.0

In [11]:
df_0 = pd.read_csv('/content/sample_data/california_housing_test.csv',
                 index_col=0 # la columna 0 sea la columna indice
                 )
df_0.head()

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
longitude,,,,,,,,
-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [12]:
# guardar csv
df.to_csv('nuevo_archivo.csv')

### Accediendo al datafram

In [13]:
df.sample(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
1587,-118.22,33.96,42.0,1380.0,331.0,1290.0,288.0,2.8000,161800.0
527,-122.45,38.01,36.0,4501.0,832.0,2196.0,800.0,4.3182,252700.0
1942,-118.03,33.93,35.0,2470.0,416.0,1386.0,411.0,5.2736,179500.0

In [14]:
# formas de acceder a las columnas
# df.total_bedrooms
df['total_bedrooms']

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [15]:
# Acceder a las filas de las columnas
df['total_bedrooms'][0]

661.0

In [16]:
# acceder a toda la fila (la primera)
df.iloc[0]

longitude               -122.0500
latitude                  37.3700
housing_median_age        27.0000
total_rooms             3885.0000
total_bedrooms           661.0000
population              1537.0000
households               606.0000
median_income              6.6085
median_house_value    344700.0000
Name: 0, dtype: float64

In [17]:
# Todas las filas de la columna 0
df.iloc[:, 0]

0      -122.05
1      -118.30
2      -117.81
3      -118.36
4      -119.67
         ...
2995   -119.86
2996   -118.14
2997   -119.70
2998   -117.12
2999   -119.63
Name: longitude, Length: 3000, dtype: float64

In [18]:
# 3 primeras filas de la columna 0
df.iloc[:3, 0]
# df.iloc[[0,1,2], 0]

0   -122.05
1   -118.30
2   -117.81
Name: longitude, dtype: float64

In [19]:
# la 3 ultimas filas de la columna 0
df.iloc[-3:, 0]

2997   -119.70
2998   -117.12
2999   -119.63
Name: longitude, dtype: float64

In [20]:
# seleccionando fila y columna con el nombre de la columna
df.loc[0, 'total_bedrooms']
# df['total_bedrooms'][0] #lo mismo

661.0

In [21]:
# selecciona las filas de varias columnas. para ver solo 5 uso head()
df.loc[:, ['total_bedrooms', 'total_rooms']].head()

   total_bedrooms  total_rooms
0           661.0       3885.0
1           310.0       1510.0
2           507.0       3589.0
3            15.0         67.0
4           244.0       1241.0

In [ ]:
# Puedo definir una columna como index
df.set_index('longitude')

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
longitude,,,,,,,,
-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...
-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
#Filtrando filas segun condicionales
df.loc[df['total_bedrooms']==661]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
444,-117.66,34.11,19.0,3445.0,661.0,1635.0,580.0,5.0681,230500.0
1316,-118.47,34.24,19.0,2405.0,661.0,1855.0,621.0,2.3111,255400.0
1415,-117.14,32.76,35.0,2539.0,661.0,1308.0,629.0,2.6777,146400.0
2140,-118.36,34.03,40.0,2323.0,661.0,1847.0,614.0,1.8316,113500.0

In [ ]:
# segun dos condiciones
df.loc[(df['total_bedrooms']<=700) & #and
       (df['total_bedrooms']>=300)]

df.loc[(df['total_bedrooms']==700) | # or
       (df['total_bedrooms']==300)]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
411,-118.19,34.14,38.0,1826.0,300.0,793.0,297.0,5.2962,291500.0
613,-119.84,36.75,34.0,1186.0,300.0,774.0,271.0,1.5750,57100.0
828,-119.05,34.35,39.0,950.0,300.0,1366.0,312.0,2.2443,146600.0
1107,-118.54,34.27,28.0,2309.0,300.0,931.0,302.0,6.7415,348200.0
1244,-118.36,33.81,26.0,1575.0,300.0,881.0,309.0,5.1778,359900.0
1859,-122.86,40.56,12.0,1350.0,300.0,423.0,172.0,1.7393,81300.0
2681,-117.88,33.72,38.0,1421.0,300.0,1236.0,263.0,3.9844,165300.0
2732,-119.60,36.58,28.0,1452.0,300.0,919.0,308.0,2.8287,73100.0

In [ ]:
# filtro dentro de una lista
df.loc[df['total_rooms'].isin([100,200,300,400,500,600])]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
715,-118.22,33.91,27.0,500.0,159.0,732.0,162.0,2.7426,103100.0
1050,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0
1218,-122.09,37.69,43.0,500.0,110.0,273.0,120.0,3.3125,150000.0

In [ ]:
# Encontrando valores nulos
df.loc[df['total_bedrooms'].isnull()]
# Encontrando valores NO nulos
df.loc[df['total_bedrooms'].notnull()]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
# filtrar utilizando query
# personalmente mi forma favorita de filtrar filas
df.query('total_rooms in [100,200,300,400,500,600]')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
715,-118.22,33.91,27.0,500.0,159.0,732.0,162.0,2.7426,103100.0
1050,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0
1218,-122.09,37.69,43.0,500.0,110.0,273.0,120.0,3.3125,150000.0

In [ ]:
# agregabdo una nueva olumna con un nuevo valor
df['nueva_columna'] = 'valores nuevos'
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,nueva_columna
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,valores nuevos
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,valores nuevos
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,valores nuevos
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,valores nuevos
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,valores nuevos

In [ ]:
df['indice_2'] = range(len(df),0,-1)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,nueva_columna,indice_2
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,valores nuevos,3000
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,valores nuevos,2999
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,valores nuevos,2998
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,valores nuevos,2997
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,valores nuevos,2996

### Funciones resumen

In [ ]:
df['total_rooms'].describe()

count     3000.000000
mean      2599.578667
std       2155.593332
min          6.000000
25%       1401.000000
50%       2106.000000
75%       3129.000000
max      30450.000000
Name: total_rooms, dtype: float64

In [ ]:
df['total_rooms'].mean()

2599.578666666667

In [ ]:
df['total_rooms'].unique()

array([3885., 1510., 3589., ..., 4867.,  573., 5257.])

In [ ]:
df['total_rooms'].value_counts().sort_values(ascending=False)

907.0      5
1778.0     5
1966.0     5
1787.0     5
2711.0     4
          ..
2253.0     1
11251.0    1
1708.0     1
2397.0     1
5257.0     1
Name: total_rooms, Length: 2215, dtype: int64

In [22]:
total_rooms_mean=df['total_rooms'].mean()
df['total_rooms'].map(
    lambda d: d-total_rooms_mean
)

0       1285.421333
1      -1089.578667
2        989.421333
3      -2532.578667
4      -1358.578667
           ...
2995   -1149.578667
2996    2657.421333
2997   -1643.578667
2998   -2503.578667
2999    -834.578667
Name: total_rooms, Length: 3000, dtype: float64

In [ ]:
df['total_rooms']-df['total_rooms'].mean()

0       1285.421333
1      -1089.578667
2        989.421333
3      -2532.578667
4      -1358.578667
           ...
2995   -1149.578667
2996    2657.421333
2997   -1643.578667
2998   -2503.578667
2999    -834.578667
Name: total_rooms, Length: 3000, dtype: float64

### Agrupando y ordenando datos

In [ ]:
df.groupby('housing_median_age')['housing_median_age'].count()

housing_median_age
1.0       2
2.0       6
3.0      12
4.0      28
5.0      39
6.0      25
7.0      20
8.0      25
9.0      27
10.0     30
11.0     41
12.0     41
13.0     41
14.0     57
15.0     77
16.0    107
17.0    100
18.0     76
19.0     76
20.0     63
21.0     61
22.0     60
23.0     53
24.0     75
25.0     86
26.0     88
27.0     74
28.0     58
29.0     75
30.0     76
31.0     57
32.0     91
33.0     85
34.0    102
35.0    118
36.0    115
37.0     88
38.0     64
39.0     55
40.0     43
41.0     56
42.0     51
43.0     56
44.0     51
45.0     51
46.0     41
47.0     22
48.0     34
49.0     21
50.0     16
51.0     11
52.0    173
Name: housing_median_age, dtype: int64

In [24]:
df.groupby('housing_median_age').apply(lambda d: d.nueva_columna.iloc[0])

AttributeError: ignored

In [25]:
reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()])

NameError: ignored

In [26]:
# se combierte en un multi index
df.groupby(by=['housing_median_age', 'total_rooms'], as_index=False)['median_income'].agg(['mean', 'min'])

                                   mean      min
housing_median_age total_rooms
1.0                6.0           1.6250   1.6250
                   83.0          4.8750   4.8750
2.0                158.0         2.5625   2.5625
                   200.0        15.0001  15.0001
                   718.0         4.1000   4.1000
...                                 ...      ...
52.0               4220.0        3.1901   3.1901
                   4407.0        3.3937   3.3937
                   4513.0        1.5923   1.5923
                   5604.0        4.4085   4.4085
                   6186.0        5.8543   5.8543

[2974 rows x 2 columns]

In [ ]:
df.sort_values(by='housing_median_age', ascending=False)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,nueva_columna,indice_2
2507,-118.15,33.77,52.0,2204.0,498.0,899.0,445.0,4.1765,393900.0,valores nuevos,493
1865,-122.28,37.90,52.0,2003.0,250.0,658.0,244.0,10.0825,397000.0,valores nuevos,1135
541,-117.18,32.76,52.0,2023.0,301.0,649.0,285.0,4.7396,441700.0,valores nuevos,2459
2876,-122.50,37.77,52.0,2299.0,441.0,1252.0,415.0,5.0562,336700.0,valores nuevos,124
306,-122.65,38.23,52.0,1735.0,347.0,712.0,343.0,3.1711,200800.0,valores nuevos,2694
...,...,...,...,...,...,...,...,...,...,...,...
2117,-117.51,34.16,2.0,718.0,98.0,119.0,50.0,4.1000,315000.0,valores nuevos,883
1271,-120.98,37.59,2.0,5042.0,834.0,2784.0,787.0,4.6484,145900.0,valores nuevos,1729
2429,-117.20,33.58,2.0,30450.0,5033.0,9419.0,3197.0,4.5936,174300.0,valores nuevos,571
1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0,valores nuevos,1885
842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0,valores nuevos,2158

In [ ]:
df.sort_index()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,nueva_columna,indice_2
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,valores nuevos,3000
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,valores nuevos,2999
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,valores nuevos,2998
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,valores nuevos,2997
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,valores nuevos,2996
...,...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,valores nuevos,5
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,valores nuevos,4
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,valores nuevos,3
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,valores nuevos,2
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,valores nuevos,1

### data types y missing

In [ ]:
# df['longitude'].dtype

df.dtypes

# df['longitude'].astype('str')

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
nueva_columna          object
indice_2                int64
dtype: object

In [ ]:
# encuentra los valores nulos
# df[df['longitude'].isnull()]
df[df['longitude'].isna()]

Empty DataFrame
Columns: [longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income, median_house_value, nueva_columna, indice_2]
Index: []

In [ ]:
df['longitude'].fillna('vacio')

0      -122.05
1      -118.30
2      -117.81
3      -118.36
4      -119.67
         ...
2995   -119.86
2996   -118.14
2997   -119.70
2998   -117.12
2999   -119.63
Name: longitude, Length: 3000, dtype: float64

In [ ]:
  df['total_bedrooms'].replace(300, 0)

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

### Renombrar y combinar

In [ ]:
df.sample()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,nueva_columna,indice_2
1780,-122.42,37.76,52.0,4407.0,1192.0,2280.0,1076.0,3.3937,270000.0,valores nuevos,1220

In [ ]:
df.rename(columns={'total_rooms':'total_cuartos'})

,longitude,latitude,housing_median_age,total_cuartos,total_bedrooms,population,households,median_income,median_house_value,nueva_columna,indice_2
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,valores nuevos,3000
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,valores nuevos,2999
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,valores nuevos,2998
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,valores nuevos,2997
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,valores nuevos,2996
...,...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,valores nuevos,5
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,valores nuevos,4
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,valores nuevos,3
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,valores nuevos,2
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,valores nuevos,1

In [ ]:
# cambio de nombre el indice
df.rename(index={0:'zero', 1:'uno'})

In [ ]:
df.rename_axis('indices', axis='rows').rename_axis('parametros',  axis='columns')

parametros,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,nueva_columna,indice_2
indices,,,,,,,,,,,
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,valores nuevos,3000
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,valores nuevos,2999
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,valores nuevos,2998
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,valores nuevos,2997
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,valores nuevos,2996
...,...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,valores nuevos,5
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,valores nuevos,4
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,valores nuevos,3
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,valores nuevos,2
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,valores nuevos,1

In [ ]:
# para combinar datasets

df_1 = pd.DataFrame({'id':['a1','a2','a3','a4', 'a5'], 'sueldo':[1200, 1500, 2500, 2000, 2300]})
df_2 = pd.DataFrame({'id':['a6','a7','a8','a9'], 'sueldo':[1200, 1500, 2500, 2000]})
df_3 = pd.DataFrame({'id':['a1','a2','a3','a4'], 'edad':[23, 21, 25, 20]})

In [ ]:
pd.concat([df_1, df_2])

   id  sueldo
0  a1    1200
1  a2    1500
2  a3    2500
3  a4    2000
4  a5    2300
0  a6    1200
1  a7    1500
2  a8    2500
3  a9    2000

In [ ]:
df_1.join(df_3, lsuffix='_1',rsuffix='_3')

  id_1  sueldo id_3  edad
0   a1    1200   a1  23.0
1   a2    1500   a2  21.0
2   a3    2500   a3  25.0
3   a4    2000   a4  20.0
4   a5    2300  NaN   NaN